version: 2

builds:
- main: ./cmd/tmplr/main.go
  ldflags:
    - -w -extldflags "-static"
    - -X github.com/atomicptr/tmplr/pkg/meta.Version={{.Version}}
    - -X github.com/atomicptr/tmplr/pkg/meta.GitCommit={{.FullCommit}}
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
  - id: default
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# Release

## Github Releases
release:
  github:
    owner: atomicptr
    name: tmplr
  draft: false

## AUR
aurs:
  - name: tmplr-bin
    homepage: &homepage "https://github.com/atomicptr/tmplr"
    description: &description |
      Quickly create new files from templates
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/tmplr-bin.git"
    provides:
      - tmplr
    commit_author:
      name: Christopher Kaster
      email: me@atomicptr.de
    maintainers: &maintainers
      - &maintainer "Christopher Kaster <me@atomicptr.de>"
    license: &license GPL-3.0-or-later

## Nix:
nix:
  - name: tmplr
    repository:
      owner: atomicptr
      name: nix
      branch: master
    homepage: *homepage
    description: *description
    license: gpl3

## Homebrew
brews:
  - name: tmplr
    repository:
      owner: atomicptr
      name: homebrew-tools
    directory: Formula
    homepage: *homepage
    description: *description
    license: *license

## Scoop
scoops:
  - name: tmplr
    repository:
      owner: atomicptr
      name: scoop-bucket
    homepage: *homepage
    description: *description
    license: *license

## NFPM (deb and rpm)
nfpms:
  - package_name: tmplr
    vendor: atomicptr
    formats:
      - deb
      - rpm
    homepage: *homepage
    description: *description
    license: *license
    maintainer: *maintainer
