on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  tests:
    name: CI Tests & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - name: Install Dependencies
        run: |
          go install github.com/mattn/goveralls@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1
      - name: Build & Test
        run: |
          make build
          go test -v -covermode=count -coverprofile=coverage.out ./...
          $(go env GOPATH)/bin/golangci-lint run ./...
      - name: Release Prep
        run: |
          git checkout -- go.mod go.sum
          apt install nix-prefetch-url
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
